"""recreate tables

Revision ID: 488fe85337eb
Revises: 
Create Date: 2023-08-15 14:15:15.794706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488fe85337eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('type_alias', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('type_alias', sa.String(), nullable=True),
    sa.Column('idol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idol_id'], ['idol.id'], name=op.f('fk_user_idol_id_idol')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('idol')
    # ### end Alembic commands ###
