"""update tables

Revision ID: a09e56d00ba7
Revises: 0122657a2db3
Create Date: 2023-08-15 12:33:04.317271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09e56d00ba7'
down_revision: Union[str, None] = '0122657a2db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idol', sa.Column('type_alias', sa.String(), nullable=True))
    op.add_column('idol', sa.Column('match_type', sa.String(), nullable=True))
    op.add_column('user', sa.Column('type_alias', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type_alias')
    op.drop_column('idol', 'match_type')
    op.drop_column('idol', 'type_alias')
    # ### end Alembic commands ###
