"""rerecreate tables

Revision ID: 35d5aee1a681
Revises: 
Create Date: 2023-08-17 12:49:06.921278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d5aee1a681'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('type_alias', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('type_alias', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idol_user',
    sa.Column('idol_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idol_id'], ['idol.id'], name=op.f('fk_idol_user_idol_id_idol')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_idol_user_user_id_user')),
    sa.PrimaryKeyConstraint('idol_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idol_user')
    op.drop_table('user')
    op.drop_table('idol')
    # ### end Alembic commands ###
